
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Uranus'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'Uranus'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
# test-paths: ["tests"]  # Disabled tests for now
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Configure all models to be built as views (not materialized)
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  Uranus:
    # Config indicated by + and applies to all files under models/
    +materialized: view
