Uranus:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: default
      password: ""
      database: default
      schema: default
      secure: false
      verify: false
      connect_timeout: 10
      send_receive_timeout: 300
      sync_request_timeout: 5
      compress: true
      settings:
        use_numpy: true
