services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packetpulse_network

  kafka:
    image: confluentinc/cp-kafka:7.2.15
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - packetpulse_network

  venus:
    build:
      context: ..
      dockerfile: Venus/Dockerfile
    container_name: venus
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=sessions
      - KAFKA_CONSUMER_GROUP=venus
      - MAX_CONNECTIONS=1000
      - API_KEY=mars-secret-key
    networks:
      - packetpulse_network

  mars:
    build:
      context: ..
      dockerfile: Mars/Dockerfile
    container_name: mars
    depends_on:
      - venus
    environment:
      - WEBSOCKET_URL=ws://venus:8000/ws
      - API_KEY=mars-secret-key
      - TOTAL_SESSIONS=50
    restart: "no"
    networks:
      - packetpulse_network

networks:
  packetpulse_network:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
