
version: 2

models:
  - name: active_sessions
    description: "Active delivery sessions with real-time location and ETA information"
    columns:
      - name: session_id
        description: "Unique identifier for the session"
      - name: vehicle_id
        description: "Unique identifier for the vehicle"
      - name: order_id
        description: "Unique identifier for the order"
      - name: order_status
        description: "Current status of the order"
      - name: start_time
        description: "Timestamp when the session started"
      - name: last_update_time
        description: "Timestamp of the latest movement update"
      - name: current_lat
        description: "Current latitude of the vehicle"
      - name: current_lon
        description: "Current longitude of the vehicle"
      - name: distance_to_destination_km
        description: "Remaining distance to destination in kilometers"
      - name: elapsed_time
        description: "Time elapsed since session start (HH:MM:SS format)"
      - name: avg_speed_kmh
        description: "Average speed in kilometers per hour"
      - name: eta
        description: "Estimated time to arrival (HH:MM:SS format)"

  - name: session_summary
    description: "Summary statistics for delivery sessions (completed and active with movements)"
    columns:
      - name: session_id
        description: "Unique identifier for the session"
      - name: vehicle_id
        description: "Unique identifier for the vehicle"
      - name: order_id
        description: "Unique identifier for the order"
      - name: status
        description: "Current status of the session (from latest movement or order completion)"
      - name: start_time
        description: "Timestamp when the session started (UTC)"
      - name: end_time
        description: "Timestamp when the session ended (UTC) - either completion time or latest movement"
      - name: duration_seconds
        description: "Total duration of the session in seconds"
      - name: total_distance_km
        description: "Total distance traveled in kilometers (rounded to 2 decimals)"
      - name: avg_speed_kmh
        description: "Average speed during the session in kilometers per hour (rounded to 2 decimals)"

  - name: kpi_aggregates
    description: "Aggregated KPIs by time period (daily, weekly, monthly)"
    columns:
      - name: period_start
        description: "Start of the aggregation period"
      - name: period_end
        description: "End of the aggregation period"
      - name: period_type
        description: "Type of period (day, week, month)"
      - name: sessions_completed
        description: "Number of sessions completed in the period"
      - name: avg_duration_sec
        description: "Average session duration in seconds"
      - name: total_distance_km
        description: "Total distance traveled in kilometers"
      - name: avg_speed_kmh
        description: "Average speed across all sessions in kilometers per hour"

  - name: fleet_summary
    description: "Fleet management view with vehicle statistics and performance metrics"
    columns:
      - name: vehicle_id
        description: "Unique identifier for the vehicle"
      - name: first_seen
        description: "Timestamp when the vehicle was first observed"
      - name: last_updated
        description: "Timestamp of the last activity for this vehicle"
      - name: is_active
        description: "Whether the vehicle is currently active"
      - name: trips
        description: "Number of completed trips for this vehicle"
      - name: total_km
        description: "Total distance traveled by this vehicle in kilometers"

  - name: users
    description: "User authentication table for dashboard access"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
      - name: username
        description: "Username for login"
      - name: email
        description: "User's email address"
      - name: password_hash
        description: "Hashed password for security"
      - name: created_at
        description: "Timestamp when the user was created"
      - name: updated_at
        description: "Timestamp when the user was last updated"
      - name: is_active
        description: "Whether the user account is active"
